const languages = {
    en: {
        title: "Account Center - CIB",
        menu: "Menu",
        profile: "Profile Info",
        settings: "Account Settings",
        activity: "Activity History",
        username: "Username:",
        phone: "Phone Number:",
        password: "Password:",
        editButton: "Edit Profile",
        changePassword: "Change Password:",
        preferredLanguage: "Preferred Language:",
        notifications: "Notifications:",
        receiveNotifications: "Receive email notifications",
        saveButton: "Save Changes",
        date: "Date",
        activityHeader: "Activity",
        status: "Status"
    },
    es: {
        title: "Centro de Cuentas - CIB",
        menu: "Menú",
        profile: "Información del Perfil",
        settings: "Configuraciones de Cuenta",
        activity: "Historial de Actividad",
        username: "Nombre de Usuario:",
        phone: "Número de Teléfono:",
        password: "Contraseña:",
        editButton: "Editar Perfil",
        changePassword: "Cambiar Contraseña:",
        preferredLanguage: "Idioma Preferido:",
        notifications: "Notificaciones:",
        receiveNotifications: "Recibir notificaciones por correo electrónico",
        saveButton: "Guardar Cambios",
        date: "Fecha",
        activityHeader: "Actividad",
        status: "Estado"
    },
    ar: {
        title: "مركز الحسابات - CIB",
        menu: "القائمة",
        profile: "معلومات الملف الشخصي",
        settings: "إعدادات الحساب",
        activity: "سجل النشاط",
        username: "اسم المستخدم:",
        phone: "رقم الهاتف:",
        password: "كلمة المرور:",
        editButton: "تعديل الملف الشخصي",
        changePassword: "تغيير كلمة المرور:",
        preferredLanguage: "اللغة المفضلة:",
        notifications: "الإشعارات:",
        receiveNotifications: "تلقي إشعارات البريد الإلكتروني",
        saveButton: "حفظ التغييرات",
        date: "التاريخ",
        activityHeader: "النشاط",
        status: "الحالة"
    },
    fr: {
        title: "Centre de Compte - CIB",
        menu: "Menu",
        profile: "Informations du Profil",
        settings: "Paramètres du Compte",
        activity: "Historique des Activités",
        username: "Nom d'utilisateur:",
        phone: "Numéro de Téléphone:",
        password: "Mot de Passe:",
        editButton: "Modifier le Profil",
        changePassword: "Changer le Mot de Passe:",
        preferredLanguage: "Langue Préférée:",
        notifications: "Notifications:",
        receiveNotifications: "Recevoir les notifications par e-mail",
        saveButton: "Enregistrer les Modifications",
        date: "Date",
        activityHeader: "Activité",
        status: "Statut"
    }
    // Add more languages as needed
};
